'use client';

import { motion } from 'framer-motion';
import Image from 'next/image';

interface HeroSectionProps {
  featuredSticker?: {
    id: number;
    title: string;
    image_filename: string;
  };
}

export default function HeroSection({ featuredSticker }: HeroSectionProps) {

  const handleExploreCollection = () => {
    // Scroll to the collection section on the same page
    const collectionSection = document.getElementById('collection');
    if (collectionSection) {
      collectionSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  const handleViewPricing = () => {
    // Scroll to the pricing section on the same page
    const pricingSection = document.getElementById('pricing');
    if (pricingSection) {
      pricingSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  return (
    <section className="relative pt-24 pb-32 px-4 sm:px-6 lg:px-8 bg-gradient-to-b from-white via-gray-50/50 to-white overflow-hidden">
      {/* Subtle background decoration */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-cyan-500/5 rounded-full blur-3xl"></div>
        <div className="absolute top-0 right-1/4 w-96 h-96 bg-purple-500/5 rounded-full blur-3xl"></div>
      </div>

      <div className="relative max-w-7xl mx-auto">
        <div className="grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">
          {/* Left: Text Content */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8, ease: 'easeOut' }}
            className="space-y-8"
          >
            {/* Badge */}
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1, duration: 0.6 }}
            >
              <span className="inline-flex items-center gap-2 px-4 py-2 bg-gray-100 rounded-full text-sm font-medium text-gray-700">
                <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
                Daily AI Stickers
              </span>
            </motion.div>

            {/* Main Title */}
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2, duration: 0.8, ease: 'easeOut' }}
              className="text-5xl sm:text-6xl lg:text-7xl font-bold text-gray-900 leading-[1.1] tracking-tight"
            >
              The Daily{' '}
              <span className="bg-gradient-to-r from-gray-900 via-gray-700 to-gray-900 bg-clip-text text-transparent">
                Sticker Archive
              </span>
            </motion.h1>

            {/* Description */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3, duration: 0.8, ease: 'easeOut' }}
              className="space-y-4"
            >
              <p className="text-xl sm:text-2xl text-gray-600 leading-relaxed">
                Production-ready vector stickers generated by AI. Every sticker comes with the exact prompt that created it.
              </p>
              <p className="text-lg text-gray-500 leading-relaxed">
                Browse our collection of die-cut vector stickers. Copy prompts, remix ideas, and discover what&apos;s possible with AI-generated sticker designs.
              </p>
            </motion.div>

            {/* CTA Buttons */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4, duration: 0.8, ease: 'easeOut' }}
              className="flex flex-wrap items-center gap-4 pt-4"
            >
              <motion.button
                onClick={handleExploreCollection}
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                className="px-6 py-3 bg-gray-900 text-white rounded-lg font-medium hover:bg-gray-800 transition-colors shadow-lg shadow-gray-900/10"
              >
                Explore Collection
              </motion.button>
              <motion.button
                onClick={handleViewPricing}
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                className="px-6 py-3 bg-white text-gray-900 rounded-lg font-medium border border-gray-200 hover:border-gray-300 transition-colors"
              >
                View Pricing
              </motion.button>
            </motion.div>

            {/* Stats - Horizontal Layout */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5, duration: 0.8, ease: 'easeOut' }}
              className="flex flex-wrap items-center gap-8 pt-8 border-t border-gray-200"
            >
              <div>
                <div className="text-2xl font-bold text-gray-900">10+</div>
                <div className="text-sm text-gray-500 mt-1">Stickers</div>
              </div>
              <div className="w-px h-8 bg-gray-200"></div>
              <div>
                <div className="text-2xl font-bold text-gray-900">Daily</div>
                <div className="text-sm text-gray-500 mt-1">New Drops</div>
              </div>
              <div className="w-px h-8 bg-gray-200"></div>
              <div>
                <div className="text-2xl font-bold text-gray-900">100%</div>
                <div className="text-sm text-gray-500 mt-1">Prompts Included</div>
              </div>
            </motion.div>
          </motion.div>

          {/* Right: Featured Sticker Preview */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.3, duration: 0.8, ease: 'easeOut' }}
            className="relative"
          >
            {featuredSticker ? (
              <div className="relative">
                {/* Glow effect */}
                <div className="absolute inset-0 bg-gradient-to-r from-cyan-500/20 to-purple-500/20 rounded-3xl blur-2xl transform scale-110"></div>
                
                {/* Card */}
                <motion.div
                  animate={{ y: [0, -10, 0] }}
                  transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
                  className="relative bg-white rounded-2xl shadow-2xl border border-gray-200 overflow-hidden"
                >
                  <div className="relative aspect-square w-full bg-gray-50">
                    <Image
                      src={`/stickers/${featuredSticker.image_filename}`}
                      alt={featuredSticker.title}
                      fill
                      className="object-contain p-8"
                      priority
                    />
                  </div>
                  <div className="p-6 bg-white border-t border-gray-100">
                    <h3 className="text-lg font-semibold text-gray-900 mb-2">
                      {featuredSticker.title}
                    </h3>
                    <p className="text-sm text-gray-500">
                      Today&apos;s Featured Sticker
                    </p>
                  </div>
                </motion.div>
              </div>
            ) : (
              <div className="relative aspect-square w-full bg-gradient-to-br from-gray-100 to-gray-200 rounded-2xl flex items-center justify-center">
                <div className="text-center space-y-2">
                  <div className="w-16 h-16 mx-auto bg-gray-300 rounded-xl"></div>
                  <p className="text-sm text-gray-500">Featured Sticker</p>
                </div>
              </div>
            )}
          </motion.div>
        </div>
      </div>
    </section>
  );
}
